volumes:
  elastic-data:

networks:
  elastic-data:

version: '3'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    environment:
      - discovery.type=single-node
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    networks:
      - elastic-data
    ports:
      - '9200:9200'
      - '9300:9300'
    deploy:
      resources:
        limits:
          memory: 4G
