name: Python

on: [push]

jobs:
  validate:

    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        pip install --user pipenv
        pipenv install --dev

    - name: Check formatting
      run: pipenv run black . --check

    - name: Check static typing
      run: pipenv run mypy .

    - name: Run tests
      run: pipenv run pytest
